export const mockListings = [
  {
    id: 1,
    title: "Modern 2BR Apartment in Old Town",
    city: "Vilnius",
    type: "Apartment",
    price: 189000,
    beds: 2,
    baths: 1,
    area_m2: 52,
    address: "Pilies g.",
    description: "Bright renovated apartment, walking distance to everything.",
    image_url: "/images/listings/old-town-2br.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Family House with Garden",
    city: "Kaunas",
    type: "House",
    price: 279000,
    beds: 4,
    baths: 2,
    area_m2: 140,
    address: "Žaliakalnis",
    description: "Quiet street, large garden, good schools nearby.",
    image_url: "/images/listings/kaunas-house.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: "New-build Studio Near City Center",
    city: "Vilnius",
    type: "Apartment",
    price: 99000,
    beds: 1,
    baths: 1,
    area_m2: 27,
    address: "Naujamiestis",
    description: "Perfect for investment or first home.",
    image_url: "/images/listings/studio.jpg",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
